export const Node_Config_Name = {
  NODE_CIRCLE: "NODE_CIRCLE",
  NODE_CIRCLE_BORDER: "NODE_CIRCLE_BORDER",
  NODE_ICON: "NODE_ICON",
  NODE_EFFECT: "NODE_EFFECT",
  COLOR: 0xffffff,
  DELIMETER: "::",
  NODE_LABEL_BACKGROUND: "NODE_LABEL_BACKGROUND",
  NODE_LABEL_TEXT: "NODE_LABEL_TEXT",
  EDGE_LINE: "EDGE_LINE",
  WORLD_PADDING: 100,
};
